
import { Dictionary } from './types';

export const TRANSLATIONS: Dictionary = {
  en: {
    title: "SuaroBanjir",
    sendSOS: "SEND SOS",
    iAmSafe: "I AM SAFE",
    name: "Full Name",
    phone: "Phone Number",
    landmark: "Nearby Landmark / Details",
    landmarkPlaceholder: "Example: In front of masjid, behind school...",
    location: "GPS Location",
    submit: "Request Help Now",
    viewMap: "View Map",
    gettingLocation: "Acquiring GPS...",
    locationFound: "Location Locked",
    locationError: "Location Failed (Enable GPS)",
    rescuerView: "Rescue Radar",
    distance: "Distance",
    status: "Status",
    timeSubmitted: "Time Submitted",
    markSafe: "Mark as Safe",
    markRescued: "Mark as Rescued",
    noSOS: "No SOS signals found for this filter.",
    yourSOS: "Your Active SOS",
    language: "Language",
    changeLang: "Change Language",
    leagueTab: "Rescuer League",
    rescuerLeague: "Hero Leaderboard",
    rank: "Rank",
    rescuerName: "Rescuer Name",
    rescues: "Rescues",
    registerRescuer: "Register as Rescuer",
    joinTeam: "Join the Rescue Team",
    enterRescuerDetails: "Create your profile to get a Rescuer ID.",
    registerAndRescue: "Register & Get ID",
    cancel: "Cancel",
    editSOS: "Edit Details",
    updateSOS: "Update Request",
    medicalEmergencyLabel: "Disabled people, elders that require health emergency",
    filterAll: "All",
    filterActive: "Active",
    filterSafe: "Safe",
    filterRescued: "Rescued",
    modeSOS: "I Need Help (SOS)",
    modeRescue: "I Can Help (Rescuer)",
    iWantToRescue: "I Want to Be a Rescuer",
    chat: "Chat",
    sendMessage: "Send",
    typeMessage: "Type a message...",
    chatWith: "Chat with",
    rescuerLabel: "Rescuer",
    victimLabel: "Victim",
    sortBy: "Sort By",
    sortTime: "Time",
    sortDistance: "Distance",
    adminDashboard: "Admin Dashboard (View Global Map)",
    username: "Username",
    rescuerId: "Rescuer ID",
    sincereRescue: "Sincere Rescue (No ID)",
    enterIdToRescue: "Enter your Rescuer ID to claim this rescue:",
    yourIdIs: "YOUR RESCUER ID IS:",
    idNote: "Please save this ID. You will need it to record your rescues.",
    verifyAndRescue: "Verify ID & Confirm",
    invalidId: "Invalid ID. Please check or use Sincere Rescue.",
    registerSuccess: "Registration Successful!",
    sincereTeamName: "Sincere Rescue Team"
  },
  ms: {
    title: "SuaroBanjir",
    sendSOS: "HANTAR SOS",
    iAmSafe: "SAYA SELAMAT",
    name: "Nama Penuh",
    phone: "Nombor Telefon",
    landmark: "Mercu Tanda / Butiran",
    landmarkPlaceholder: "Contoh: Depan masjid, belakang sekolah...",
    location: "Lokasi GPS",
    submit: "Minta Bantuan Sekarang",
    viewMap: "Lihat Peta",
    gettingLocation: "Mencari GPS...",
    locationFound: "Lokasi Ditemui",
    locationError: "Gagal Lokasi (Aktifkan GPS)",
    rescuerView: "Radar Penyelamat",
    distance: "Jarak",
    status: "Status",
    timeSubmitted: "Masa Dihantar",
    markSafe: "Tanda Selamat",
    markRescued: "Tanda Diselamatkan",
    noSOS: "Tiada isyarat SOS untuk penapis ini.",
    yourSOS: "SOS Aktif Anda",
    language: "Bahasa",
    changeLang: "Tukar Bahasa",
    leagueTab: "Liga Penyelamat",
    rescuerLeague: "Carta Wira",
    rank: "Kedudukan",
    rescuerName: "Nama Penyelamat",
    rescues: "Penyelamatan",
    registerRescuer: "Daftar sebagai Penyelamat",
    joinTeam: "Sertai Pasukan Penyelamat",
    enterRescuerDetails: "Cipta profil untuk dapatkan ID Penyelamat.",
    registerAndRescue: "Daftar & Dapatkan ID",
    cancel: "Batal",
    editSOS: "Kemaskini Maklumat",
    updateSOS: "Kemaskini Permintaan",
    medicalEmergencyLabel: "OKU, warga emas yang memerlukan kecemasan kesihatan",
    filterAll: "Semua",
    filterActive: "Aktif",
    filterSafe: "Selamat",
    filterRescued: "Diselamatkan",
    modeSOS: "Saya Perlu Bantuan (SOS)",
    modeRescue: "Saya Boleh Bantu (Penyelamat)",
    iWantToRescue: "Saya Nak Jadi Penyelamat",
    chat: "Sembang",
    sendMessage: "Hantar",
    typeMessage: "Taip mesej...",
    chatWith: "Sembang dengan",
    rescuerLabel: "Penyelamat",
    victimLabel: "Mangsa",
    sortBy: "Susun Ikut",
    sortTime: "Masa",
    sortDistance: "Jarak",
    adminDashboard: "Papan Pemuka Admin (Lihat Peta Global)",
    username: "Nama Pengguna",
    rescuerId: "ID Penyelamat",
    sincereRescue: "Penyelamatan Ikhlas (Tiada ID)",
    enterIdToRescue: "Masukkan ID Penyelamat anda:",
    yourIdIs: "ID PENYELAMAT ANDA:",
    idNote: "Sila simpan ID ini. Anda perlukannya untuk rekod penyelamatan.",
    verifyAndRescue: "Sahkan ID & Tanda",
    invalidId: "ID Tidak Sah. Sila semak atau guna Penyelamatan Ikhlas.",
    registerSuccess: "Pendaftaran Berjaya!",
    sincereTeamName: "Pasukan Ikhlas"
  },
  th: {
    title: "SuaroBanjir",
    sendSOS: "ส่ง SOS",
    iAmSafe: "ฉันปลอดภัย",
    name: "ชื่อ - นามสกุล",
    phone: "เบอร์โทรศัพท์",
    landmark: "จุดสังเกตใกล้เคียง",
    landmarkPlaceholder: "ตัวอย่าง: หน้ามัสยิด, หลังโรงเรียน...",
    location: "ตำแหน่ง GPS",
    submit: "ขอความช่วยเหลือทันที",
    viewMap: "ดูแผนที่",
    gettingLocation: "กำลังค้นหา GPS...",
    locationFound: "ระบุตำแหน่งแล้ว",
    locationError: "ระบุตำแหน่งล้มเหลว (เปิด GPS)",
    rescuerView: "เรดาร์กู้ภัย",
    distance: "ระยะทาง",
    status: "สถานะ",
    timeSubmitted: "เวลาที่ส่ง",
    markSafe: "ระบุว่าปลอดภัยแล้ว",
    markRescued: "ระบุว่าช่วยเหลือแล้ว",
    noSOS: "ไม่พบสัญญาณ SOS ในตัวกรองนี้",
    yourSOS: "SOS ที่ใช้งานอยู่ของคุณ",
    language: "ภาษา",
    changeLang: "เปลี่ยนภาษา",
    leagueTab: "ลีกกู้ภัย",
    rescuerLeague: "กระดานผู้นำฮีโร่",
    rank: "อันดับ",
    rescuerName: "ชื่อผู้กู้ภัย",
    rescues: "จำนวนที่ช่วย",
    registerRescuer: "ลงทะเบียนเป็นผู้กู้ภัย",
    joinTeam: "เข้าร่วมทีมกู้ภัย",
    enterRescuerDetails: "สร้างโปรไฟล์เพื่อรับ ID กู้ภัย",
    registerAndRescue: "ลงทะเบียนและรับ ID",
    cancel: "ยกเลิก",
    editSOS: "แก้ไขรายละเอียด",
    updateSOS: "อัปเดตคำขอ",
    medicalEmergencyLabel: "ผู้พิการ ผู้สูงอายุ ที่ต้องการความช่วยเหลือฉุกเฉินทางสุขภาพ",
    filterAll: "ทั้งหมด",
    filterActive: "กำลังรอ",
    filterSafe: "ปลอดภัย",
    filterRescued: "ช่วยเหลือแล้ว",
    modeSOS: "ฉันต้องการความช่วยเหลือ (SOS)",
    modeRescue: "ฉันสามารถช่วยได้ (กู้ภัย)",
    iWantToRescue: "ฉันอยากเป็นผู้กู้ภัย",
    chat: "แชท",
    sendMessage: "ส่ง",
    typeMessage: "พิมพ์ข้อความ...",
    chatWith: "แชทกับ",
    rescuerLabel: "ผู้กู้ภัย",
    victimLabel: "ผู้ประสบภัย",
    sortBy: "เรียงตาม",
    sortTime: "เวลา",
    sortDistance: "ระยะทาง",
    adminDashboard: "แดชบอร์ดผู้ดูแลระบบ (ดูแผนที่ทั่วโลก)",
    username: "ชื่อผู้ใช้",
    rescuerId: "ID กู้ภัย",
    sincereRescue: "ช่วยเหลือด้วยใจ (ไม่มี ID)",
    enterIdToRescue: "ป้อน ID กู้ภัยของคุณเพื่อบันทึก:",
    yourIdIs: "ID กู้ภัยของคุณคือ:",
    idNote: "โปรดบันทึก ID นี้ คุณจะต้องใช้เพื่อบันทึกการช่วยเหลือ",
    verifyAndRescue: "ยืนยัน ID และบันทึก",
    invalidId: "ID ไม่ถูกต้อง โปรดตรวจสอบหรือใช้การช่วยเหลือด้วยใจ",
    registerSuccess: "ลงทะเบียนสำเร็จ!",
    sincereTeamName: "ทีมกู้ภัยด้วยใจ"
  }
};
