
import { Dictionary } from './types';

export const TRANSLATIONS: Dictionary = {
  en: {
    title: "SuaroBanjir",
    sendSOS: "SEND SOS",
    iAmSafe: "I AM SAFE",
    name: "Full Name",
    phone: "Phone Number",
    landmark: "Nearby Landmark / Details",
    landmarkPlaceholder: "Example: In front of masjid, behind school...",
    location: "GPS Location",
    submit: "Request Help Now",
    viewMap: "View Map",
    gettingLocation: "Acquiring GPS...",
    locationFound: "Location Locked",
    locationError: "Location Failed (Enable GPS)",
    rescuerView: "Rescue Radar",
    distance: "Distance",
    status: "Status",
    timeSubmitted: "Time Submitted",
    markSafe: "Mark as Safe",
    markRescued: "Mark as Rescued",
    noSOS: "No SOS signals found for this filter.",
    yourSOS: "Your Active SOS",
    language: "Language",
    changeLang: "Change Language",
    leagueTab: "Rescuer League",
    rescuerLeague: "Hero Leaderboard",
    rank: "Rank",
    rescuerName: "Rescuer Name",
    rescues: "Rescues",
    registerRescuer: "Register as Rescuer",
    joinTeam: "Join the Rescue Team",
    enterRescuerDetails: "Create your profile to get a Rescuer ID.",
    registerAndRescue: "Register & Get ID",
    cancel: "Cancel",
    editSOS: "Edit Details",
    updateSOS: "Update Request",
    medicalEmergencyLabel: "Disabled people, elders that require health emergency",
    filterAll: "All",
    filterActive: "Active",
    filterSafe: "Safe",
    filterRescued: "Rescued",
    modeSOS: "I Need Help (SOS)",
    modeRescue: "I Can Help (Rescuer)",
    iWantToRescue: "I Want to Be a Rescuer",
    chat: "Chat",
    sendMessage: "Send",
    typeMessage: "Type a message...",
    chatWith: "Chat with",
    rescuerLabel: "Rescuer",
    victimLabel: "Victim",
    sortBy: "Sort By",
    sortTime: "Time",
    sortDistance: "Distance",
    adminDashboard: "Admin Dashboard (View Global Map)",
    username: "Username",
    rescuerId: "Rescuer ID",
    sincereRescue: "Sincere Rescue (No ID)",
    enterIdToRescue: "Enter your Rescuer ID to claim this rescue:",
    yourIdIs: "YOUR RESCUER ID IS:",
    idNote: "Please save this ID. You will need it to record your rescues.",
    verifyAndRescue: "Verify ID & Confirm",
    invalidId: "Invalid ID. Please check or use Sincere Rescue.",
    registerSuccess: "Registration Successful!",
    sincereTeamName: "Sincere Rescue Team",
    back: "Back",
    searchLocation: "Search Location",
    manualLocationHelp: "GPS failed? Search your village/street name:",
    searching: "Searching...",
    useLocation: "Use This Location",
    noResults: "No results found.",
    adminLogin: "Admin Login",
    enterPin: "Enter Password",
    login: "Login",
    logout: "Logout",
    overview: "Overview",
    dataManagement: "Data Management",
    totalVictims: "Total SOS",
    activeRequests: "Active",
    medicalNeeds: "Medical",
    totalRescuers: "Rescuers",
    delete: "Delete",
    edit: "Edit",
    confirmDelete: "Are you sure you want to delete this record?",
    password: "Password"
  },
  ms: {
    title: "SuaroBanjir",
    sendSOS: "HANTAR SOS",
    iAmSafe: "SAYA SELAMAT",
    name: "Nama Penuh",
    phone: "Nombor Telefon",
    landmark: "Mercu Tanda / Butiran",
    landmarkPlaceholder: "Contoh: Depan masjid, belakang sekolah...",
    location: "Lokasi GPS",
    submit: "Minta Bantuan Sekarang",
    viewMap: "Lihat Peta",
    gettingLocation: "Mencari GPS...",
    locationFound: "Lokasi Ditemui",
    locationError: "Gagal Lokasi (Aktifkan GPS)",
    rescuerView: "Radar Penyelamat",
    distance: "Jarak",
    status: "Status",
    timeSubmitted: "Masa Dihantar",
    markSafe: "Tanda Selamat",
    markRescued: "Tanda Diselamatkan",
    noSOS: "Tiada isyarat SOS untuk penapis ini.",
    yourSOS: "SOS Aktif Anda",
    language: "Bahasa",
    changeLang: "Tukar Bahasa",
    leagueTab: "Liga Penyelamat",
    rescuerLeague: "Carta Wira",
    rank: "Kedudukan",
    rescuerName: "Nama Penyelamat",
    rescues: "Penyelamatan",
    registerRescuer: "Daftar sebagai Penyelamat",
    joinTeam: "Sertai Pasukan Penyelamat",
    enterRescuerDetails: "Cipta profil untuk dapatkan ID Penyelamat.",
    registerAndRescue: "Daftar & Dapatkan ID",
    cancel: "Batal",
    editSOS: "Kemaskini Maklumat",
    updateSOS: "Kemaskini Permintaan",
    medicalEmergencyLabel: "OKU, warga emas yang memerlukan kecemasan kesihatan",
    filterAll: "Semua",
    filterActive: "Aktif",
    filterSafe: "Selamat",
    filterRescued: "Diselamatkan",
    modeSOS: "Saya Perlu Bantuan (SOS)",
    modeRescue: "Saya Boleh Bantu (Penyelamat)",
    iWantToRescue: "Saya Nak Jadi Penyelamat",
    chat: "Sembang",
    sendMessage: "Hantar",
    typeMessage: "Taip mesej...",
    chatWith: "Sembang dengan",
    rescuerLabel: "Penyelamat",
    victimLabel: "Mangsa",
    sortBy: "Susun Ikut",
    sortTime: "Masa",
    sortDistance: "Jarak",
    adminDashboard: "Papan Pemuka Admin (Lihat Peta Global)",
    username: "Nama Pengguna",
    rescuerId: "ID Penyelamat",
    sincereRescue: "Penyelamatan Ikhlas (Tiada ID)",
    enterIdToRescue: "Masukkan ID Penyelamat anda:",
    yourIdIs: "ID PENYELAMAT ANDA:",
    idNote: "Sila simpan ID ini. Anda perlukannya untuk rekod penyelamatan.",
    verifyAndRescue: "Sahkan ID & Tanda",
    invalidId: "ID Tidak Sah. Sila semak atau guna Penyelamatan Ikhlas.",
    registerSuccess: "Pendaftaran Berjaya!",
    sincereTeamName: "Pasukan Ikhlas",
    back: "Kembali",
    searchLocation: "Cari Lokasi",
    manualLocationHelp: "GPS Gagal? Cari nama kampung/jalan anda:",
    searching: "Mencari...",
    useLocation: "Guna Lokasi Ini",
    noResults: "Tiada keputusan ditemui.",
    adminLogin: "Log Masuk Admin",
    enterPin: "Masukkan Kata Laluan",
    login: "Log Masuk",
    logout: "Log Keluar",
    overview: "Gambaran Keseluruhan",
    dataManagement: "Pengurusan Data",
    totalVictims: "Jumlah SOS",
    activeRequests: "Aktif",
    medicalNeeds: "Perubatan",
    totalRescuers: "Penyelamat",
    delete: "Padam",
    edit: "Edit",
    confirmDelete: "Adakah anda pasti mahu memadam rekod ini?",
    password: "Kata Laluan"
  },
  th: {
    title: "SuaroBanjir",
    sendSOS: "ส่ง SOS",
    iAmSafe: "ฉันปลอดภัย",
    name: "ชื่อ - นามสกุล",
    phone: "เบอร์โทรศัพท์",
    landmark: "จุดสังเกตใกล้เคียง",
    landmarkPlaceholder: "ตัวอย่าง: หน้ามัสยิด, หลังโรงเรียน...",
    location: "ตำแหน่ง GPS",
    submit: "ขอความช่วยเหลือทันที",
    viewMap: "ดูแผนที่",
    gettingLocation: "กำลังค้นหา GPS...",
    locationFound: "ระบุตำแหน่งแล้ว",
    locationError: "ระบุตำแหน่งล้มเหลว (เปิด GPS)",
    rescuerView: "เรดาร์กู้ภัย",
    distance: "ระยะทาง",
    status: "สถานะ",
    timeSubmitted: "เวลาที่ส่ง",
    markSafe: "ระบุว่าปลอดภัยแล้ว",
    markRescued: "ระบุว่าช่วยเหลือแล้ว",
    noSOS: "ไม่พบสัญญาณ SOS ในตัวกรองนี้",
    yourSOS: "SOS ที่ใช้งานอยู่ของคุณ",
    language: "ภาษา",
    changeLang: "เปลี่ยนภาษา",
    leagueTab: "ลีกกู้ภัย",
    rescuerLeague: "กระดานผู้นำฮีโร่",
    rank: "อันดับ",
    rescuerName: "ชื่อผู้กู้ภัย",
    rescues: "จำนวนที่ช่วย",
    registerRescuer: "ลงทะเบียนเป็นผู้กู้ภัย",
    joinTeam: "เข้าร่วมทีมกู้ภัย",
    enterRescuerDetails: "สร้างโปรไฟล์เพื่อรับ ID กู้ภัย",
    registerAndRescue: "ลงทะเบียนและรับ ID",
    cancel: "ยกเลิก",
    editSOS: "แก้ไขรายละเอียด",
    updateSOS: "อัปเดตคำขอ",
    medicalEmergencyLabel: "ผู้พิการ ผู้สูงอายุ ที่ต้องการความช่วยเหลือฉุกเฉินทางสุขภาพ",
    filterAll: "ทั้งหมด",
    filterActive: "กำลังรอ",
    filterSafe: "ปลอดภัย",
    filterRescued: "ช่วยเหลือแล้ว",
    modeSOS: "ฉันต้องการความช่วยเหลือ (SOS)",
    modeRescue: "ฉันสามารถช่วยได้ (กู้ภัย)",
    iWantToRescue: "ฉันอยากเป็นผู้กู้ภัย",
    chat: "แชท",
    sendMessage: "ส่ง",
    typeMessage: "พิมพ์ข้อความ...",
    chatWith: "แชทกับ",
    rescuerLabel: "ผู้กู้ภัย",
    victimLabel: "ผู้ประสบภัย",
    sortBy: "เรียงตาม",
    sortTime: "เวลา",
    sortDistance: "ระยะทาง",
    adminDashboard: "แดชบอร์ดผู้ดูแลระบบ (ดูแผนที่ทั่วโลก)",
    username: "ชื่อผู้ใช้",
    rescuerId: "ID กู้ภัย",
    sincereRescue: "ช่วยเหลือด้วยใจ (ไม่มี ID)",
    enterIdToRescue: "ป้อน ID กู้ภัยของคุณเพื่อบันทึก:",
    yourIdIs: "ID กู้ภัยของคุณคือ:",
    idNote: "โปรดบันทึก ID นี้ คุณจะต้องใช้เพื่อบันทึกการช่วยเหลือ",
    verifyAndRescue: "ยืนยัน ID และบันทึก",
    invalidId: "ID ไม่ถูกต้อง โปรดตรวจสอบหรือใช้การช่วยเหลือด้วยใจ",
    registerSuccess: "ลงทะเบียนสำเร็จ!",
    sincereTeamName: "ทีมกู้ภัยด้วยใจ",
    back: "ย้อนกลับ",
    searchLocation: "ค้นหาตำแหน่ง",
    manualLocationHelp: "GPS ล้มเหลว? ค้นหาชื่อหมู่บ้าน/ถนนของคุณ:",
    searching: "กำลังค้นหา...",
    useLocation: "ใช้ตำแหน่งนี้",
    noResults: "ไม่พบผลลัพธ์",
    adminLogin: "เข้าสู่ระบบแอดมิน",
    enterPin: "ป้อนรหัสผ่าน",
    login: "เข้าสู่ระบบ",
    logout: "ออกจากระบบ",
    overview: "ภาพรวม",
    dataManagement: "การจัดการข้อมูล",
    totalVictims: "SOS ทั้งหมด",
    activeRequests: "กำลังรอ",
    medicalNeeds: "การแพทย์",
    totalRescuers: "ผู้กู้ภัย",
    delete: "ลบ",
    edit: "แก้ไข",
    confirmDelete: "คุณแน่ใจหรือไม่ว่าต้องการลบรายการนี้?",
    password: "รหัสผ่าน"
  },
  zh: {
    title: "SuaroBanjir",
    sendSOS: "发送求救信号",
    iAmSafe: "我很安全",
    name: "全名",
    phone: "电话号码",
    landmark: "附近地标 / 详情",
    landmarkPlaceholder: "例如：清真寺前，学校后面...",
    location: "GPS 位置",
    submit: "立即请求援助",
    viewMap: "查看地图",
    gettingLocation: "正在获取 GPS...",
    locationFound: "位置已锁定",
    locationError: "定位失败（请开启 GPS）",
    rescuerView: "救援雷达",
    distance: "距离",
    status: "状态",
    timeSubmitted: "提交时间",
    markSafe: "标记为安全",
    markRescued: "标记为已获救",
    noSOS: "在此筛选条件下未找到 SOS 信号。",
    yourSOS: "您的求救信号",
    language: "语言",
    changeLang: "更改语言",
    leagueTab: "救援联盟",
    rescuerLeague: "英雄排行榜",
    rank: "排名",
    rescuerName: "救援人员姓名",
    rescues: "救援次数",
    registerRescuer: "注册为救援人员",
    joinTeam: "加入救援队",
    enterRescuerDetails: "创建您的个人资料以获取救援人员 ID。",
    registerAndRescue: "注册并获取 ID",
    cancel: "取消",
    editSOS: "编辑详情",
    updateSOS: "更新请求",
    medicalEmergencyLabel: "残疾人士、需要健康急救的老年人",
    filterAll: "全部",
    filterActive: "活跃",
    filterSafe: "安全",
    filterRescued: "已获救",
    modeSOS: "我需要帮助 (SOS)",
    modeRescue: "我可以帮忙 (救援人员)",
    iWantToRescue: "我想成为救援人员",
    chat: "聊天",
    sendMessage: "发送",
    typeMessage: "输入消息...",
    chatWith: "与...聊天",
    rescuerLabel: "救援人员",
    victimLabel: "受害者",
    sortBy: "排序方式",
    sortTime: "时间",
    sortDistance: "距离",
    adminDashboard: "管理仪表板（查看全球地图）",
    username: "用户名",
    rescuerId: "救援人员 ID",
    sincereRescue: "真诚救援（无 ID）",
    enterIdToRescue: "输入您的救援人员 ID 以认领此次救援：",
    yourIdIs: "您的救援人员 ID 是：",
    idNote: "请保存此 ID。您将需要它来记录您的救援。",
    verifyAndRescue: "验证 ID 并确认",
    invalidId: "ID 无效。请检查或使用真诚救援。",
    registerSuccess: "注册成功！",
    sincereTeamName: "真诚救援队",
    back: "返回",
    searchLocation: "搜索位置",
    manualLocationHelp: "GPS 失败？搜索您的村庄/街道名称：",
    searching: "正在搜索...",
    useLocation: "使用此位置",
    noResults: "未找到结果。",
    adminLogin: "管理员登录",
    enterPin: "输入密码",
    login: "登录",
    logout: "注销",
    overview: "概览",
    dataManagement: "数据管理",
    totalVictims: "SOS 总数",
    activeRequests: "活跃",
    medicalNeeds: "医疗需求",
    totalRescuers: "救援人员",
    delete: "删除",
    edit: "编辑",
    confirmDelete: "您确定要删除此记录吗？",
    password: "密码"
  }
};